#!/usr/bin/env python
"""Build Supplementary Table 1 from the unfactored-correlation audit.

The table reports whether each one-factor constructed haplotype is the
highest-probability candidate when evaluated under the full working
correlation matrix. Conditional probabilities come from cond_probs_v40.json;
gaps and integration diagnostics come from verify_sparse_v33.json. The latter
retains a legacy production filename but the table is not a sparse-PCA
comparison.

This deterministic builder reads and formats released artifacts only.

Run from the repository root:
    python paper/figdata/make_supptable_ST1.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
DOC = HERE.parent                  # figdata -> paper
OUT = DOC / "supp" / "supp-tables" / "ST1_verify_mode.tex"

v33 = json.load(open(HERE / "verify_sparse_v33.json"))
rows = sorted(v33["per_locus"], key=lambda r: -r["K"])

# v33 stores the joint rectangle probability Pr(X=x, X_0=1). v40 supplies
# the normalized conditional value. Probability gaps are unchanged by the
# locus-specific normalization and are read directly from v33.
cond = {r["locus"]: r for r in json.load(open(HERE / "cond_probs_v40.json"))["per_locus"]}
assert all(r["locus"] in cond for r in rows), "cond_probs_v40.json does not cover every locus"

assert len(rows) == 27, f"expected 27 loci, got {len(rows)}"
assert v33["config"]["seeds"] == [11, 2027] and v33["config"]["eig_floors"] == [1e-06, 0.0001]

tick, cross = r"\checkmark", r"$\times$"
lines = [
    r"% GENERATED by paper/figdata/make_supptable_ST1.py -- do not edit by hand.",
    r"% Source: verify_sparse_v33.json (job 50782371).",
    r"\begin{longtable}{l r c r r r c}",
    r"\caption{\textbf{Per-locus verification of the constructed haplotype against the true "
    r"correlation matrix $\mathbf{R}$.} The haplotype is constructed from the one-factor model; its "
    r"probability is then evaluated under the \emph{unfactored} $\mathbf{R}$, so the check is not "
    r"circular. $p=k+1$ is the number of variants; $\Pr(\hat{x}\mid\mathbf{R})$ is the constructed "
    r"haplotype's probability under the full matrix, estimated by GHK; \emph{argmax} indicates it is "
    r"the highest-probability candidate in the scored set; \emph{gap} is its lead over the runner-up "
    r"in nats; \emph{gap/SE} divides that lead by the combined relative standard error of the two, "
    r"treating them as independent, which is conservative because common random numbers correlate "
    r"them positively; \emph{Genz} marks the $17$ loci small enough for the independent Genz "
    r"integrator, all of which agree on the argmax. Every verdict is identical across two seeds and "
    r"two eigenvalue floors. Source: \texttt{figdata/verify\_sparse\_v33.json} (DCC job "
    r"$50782371$).}"
    r"\label{tab:supp-verify-mode}\\",
    r"\toprule",
    r"locus & $p$ & argmax & $\Pr(\hat{x}\mid\mathbf{R},X_0{=}1)$ & gap & gap/SE & Genz \\",
    r"\midrule",
    r"\endfirsthead",
    r"\toprule",
    r"locus & $p$ & argmax & $\Pr(\hat{x}\mid\mathbf{R},X_0{=}1)$ & gap & gap/SE & Genz \\",
    r"\midrule",
    r"\endhead",
    r"\bottomrule",
    r"\endfoot",
]

n_argmax = n_genz = n_stable = 0
for r in rows:
    am = bool(r["true_R_argmax_is_dense_top1"])
    n_argmax += am
    n_stable += bool(r["verdict_stable_across_seeds_and_floors"])
    gz = r["genz_cross_check"]
    if gz:
        n_genz += gz["same_argmax"]
    gap = "--" if r["true_R_logp_gap"] is None else f"{r['true_R_logp_gap']:.2f}"
    gse = "--" if not r.get("true_R_gap_over_se") else f"{r['true_R_gap_over_se']:.0f}"
    lines.append(
        f"\\texttt{{{r['locus'].replace('_', chr(92)+'_')}}} & {r['K']} & "
        f"{tick if am else cross} & {cond[r['locus']]['true_R_p_top_cond']:.3f} & {gap} & {gse} & "
        f"{tick if gz and gz['same_argmax'] else ('--' if not gz else cross)} \\\\"
    )
lines.append(r"\end{longtable}")

# The table's own claims, asserted rather than eyeballed.
assert n_argmax == 27, f"the mode is the true-R argmax at only {n_argmax} of 27 loci"
assert n_genz == 17, f"Genz agrees at only {n_genz} of the 17 loci it covers"
assert n_stable == 27, f"verdict is seed/floor-stable at only {n_stable} of 27 loci"
assert all(0.0 < cond[r["locus"]]["true_R_p_top_cond"] <= 1.0 + 1e-9 for r in rows), \
    "a conditional probability is outside (0, 1] -- the p_0 normalisation is wrong"
assert all(r["R0"] == r["K"] for r in rows), \
    "a locus has R0 < p -- the sparse/dense distinction would no longer be vacuous, so retiring " \
    "sparse PCA from the paper would need revisiting (see docs/development_history.md)"

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print("wrote", OUT)
print(f"  27 rows; true-R argmax at {n_argmax}/27; Genz agrees at {n_genz}/17; "
      f"seed/floor-stable at {n_stable}/27")
